### ISSUE TITLE
Bug with displayname command

### ISSUE THREAD

**Issue by Timmy109** [MrEAlderson/EssentialsWarpGUI#11]
There is just a typo here where it says `/displayname` it should say `/warpcfg`.

Just thought I'd let you know!!

![bug](https://user-images.githubusercontent.com/64758572/158021906-edd57d94-c77d-4f21-a030-3b943ad7154d.png)

**Comment by Timmy109** [comment]
This seems to be a common thing 

![image](https://user-images.githubusercontent.com/64758572/158022020-9a76e344-e499-442a-8de2-d96183455fe6.png)

**Comment by MrEAlderson** [comment]
Has been 'fixed' with https://github.com/MrEAlderson/EssentialsWarpGUI/commit/9ecc7cf466a0efa83dd7992ee5c18cae522a49aa
