### ISSUE TITLE
CRITICAL - Warps command is not cancelable by WorldGuard

### ISSUE THREAD

**Issue by farum12** [MrEAlderson/EssentialsWarpGUI#14]
We've observed that it's possible to use /warps command on WG regions, which have allowed-cmds and /warps is not one of them.
The player is not able to use /warp spawn, but he's able to use /warps and then select "Spawn". In result he'll be able to teleport outside the region, which he shouldn't be able to leave via /warp command.

First issue - /warps should be cancelable by other plugins.
Second issue - selecting any warp SHOULD NOT result in instant teleport of the player, it should check if the player is able to execute command /warp.

Server version: git-Purpur-1880 (MC: 1.19.3)

**Repro:**
1. Create any WorldGuard region.
2. Set allowed-cmds flag to any command, eg. /spawn.
3. Enter the region as a non-OP player.
4. Use /warps -> observe that WG message appears eg. "Hey! You cannot do that here!"
5. Click on any warp -> observe that the player is teleported outside the region.

**Comment by MrEAlderson** [comment]
Hello, I am working on a complete rewrite. I will take this into consideration, thank you very much!

**Comment by MrEAlderson** [comment]
Has been fixed with https://github.com/MrEAlderson/EssentialsWarpGUI/commit/9ecc7cf466a0efa83dd7992ee5c18cae522a49aa
