### ISSUE TITLE
Cannot uninstall the plugin

### ISSUE THREAD

**Issue by PrograMysT** [MrEAlderson/EssentialsWarpGUI#15]
Hello, I have a problem with Essentials Warp Gui plugin. I didnt read that it required Essentials when installing the plugin but it seemed to work without it (I could create a warp and i could also open the gui) so i wanted to edit the plugin but couldnt seem to find the plugin files (they didnt generate in plugins folder). So i decided to use a different plugin for warps, but after i removed the WarpGui.jar the command remained on the server and i could still create warps/open gui menu. I dont know how to fix this. In the console it doesnt show that the plugin is starting but i can still use it. Also i did uninstall the jar correctly and with the server off, restarted it a couple of times too. I will send the console log too.

Console Log: https://mcpaste.io/5c58285e13d7a336
Version: Mohist 1.20.1

**Comment by MrEAlderson** [comment]
Make sure to delete the correct jar file. PlugmanX may help you finding the name the file has within the plugins folder. Or you are using some other plugin that creates the GUI with that command.

**Comment by PrograMysT** [comment]
I dont think so and iam 100% sure i deleted the plugin correctly. Iam sending my plugin list.
![image](https://github.com/MrEAlderson/EssentialsWarpGUI/assets/114109438/67006c74-26e3-42bd-ace7-f5f6cfda4819)
![image](https://github.com/MrEAlderson/EssentialsWarpGUI/assets/114109438/84ff8ce3-22b6-49f5-9a78-01bfc06ba6a2)

**Comment by PrograMysT** [comment]
This is what i get when i do /warps
![2024-03-20_13 48 22](https://github.com/MrEAlderson/EssentialsWarpGUI/assets/114109438/96c1a1ea-77d2-422d-83e6-6aa03d2d3be7)

**Comment by MrEAlderson** [comment]
Commands don't come from this plugin.
