### ISSUE TITLE
Plugin cant be uninstalled

### ISSUE THREAD

**Issue by PrograMysT** [MrEAlderson/EssentialsWarpGUI#16]
Why did you close my issue when it clearly wasnt resolved?...

Here is my plugin list. 
Also an image of what i get when i do /warps
![image](https://github.com/MrEAlderson/EssentialsWarpGUI/assets/114109438/f87aa549-fdd8-4132-8ee3-7c4f4265f6e8)
![image](https://github.com/MrEAlderson/EssentialsWarpGUI/assets/114109438/f331d228-7153-4525-a8d4-6cce85bc8c55)
![2024-03-20_13 48 22](https://github.com/MrEAlderson/EssentialsWarpGUI/assets/114109438/663b3ff5-0b0e-4a3f-96da-49c332af1c39)

**Comment by MrEAlderson** [comment]
Because (and as I have described) your problem isn't related to the plugin. In fact, that screenshot shows commands that don't come from this plugin.

**Comment by PrograMysT** [comment]
I see Iam sorry for wasting your time

Dňa st 20. 3. 2024 o 14:10 Marcel ***@***.***> napísala(a):
