### ISSUE TITLE
Permission for /warpcfg bug

### ISSUE THREAD

**Issue by arboriginal** [MrEAlderson/EssentialsWarpGUI#2]
Hello,

I've set the permission "warpcfg.cfg" but I cannot use command /warpcfg.
When I check in game if I have it, it replies yes:

```
The user inherits the permission from group: g:warpgui_moderator
Permission Node: warpcfg.cfg
SuperPerms reports Node: true
```

Permissions list are up2date?

**Edit:** I can use it with /op

**Comment by MrEAlderson** [comment]
Yes, they are up-to-date.
Make sure that you have Vault installed as the plugin checks wether you are op or if Vault allows that.

**Comment by arboriginal** [comment]
I have Vault installed. **Why closing a ticket if the bug is not confirmed as resolved?**

> or if Vault allows that

Allows what?

I can use /setwarp and /delwarp, so what Vault have to do with it?
