### ISSUE TITLE
Plugin doesn't properly set the player's last location

### ISSUE THREAD

**Issue by SunburntRock89** [MrEAlderson/EssentialsWarpGUI#3]
In my experience, using /warp doesn't properly set the last location of the user which means that /back doesn't work as intended.

**Comment by MrEAlderson** [comment]
Why should essentials set the /back location when typing /warp? I'm not sure when essentials is updating the /back location but I bet that it's just saving the location of all players every x blocks he moved or every x seconda

**Comment by SunburntRock89** [comment]
AFAIK there's a function for setLastLocation of a player.
https://github.com/EssentialsX/Essentials/search?utf8=%E2%9C%93&q=setlastlocation&type=

**Comment by MrEAlderson** [comment]
Fixed it https://github.com/MrEAlderson/EssentialsWarpGUI/commit/a4170b78a796d9f3a5ad9a8c984d28bc29610a0c
