### ISSUE TITLE
/warp forced to be case-sensitive

### ISSUE THREAD

**Issue by rumplepusscat** [MrEAlderson/EssentialsWarpGUI#5]
When using /warp, the warp has to be input exactly as originally set (case-sensitive) for it to work. Otherwise, it responds with "The warp [x] doesn't exist.". This seems to be an issue with this specific plugin rather than Essentials, as using /ewarp [x] does not reproduce this same error.

Thanks!

**Comment by MrEAlderson** [comment]
Tested it on latest and it worked flawlessly
