### ISSUE TITLE
Plugin no longer works in 1.17

### ISSUE THREAD

**Issue by Budderman18** [MrEAlderson/EssentialsWarpGUI#8]
When attempting to load, it will generate the "We only support unmodified variants of Spigot and PaperSpigot or your version of spigot isn't supported." error.

**Comment by Budderman18** [comment]
Any updates on 1.17 support? Or am i better off just trying to fix it myself.

**Comment by MrEAlderson** [comment]
https://github.com/MrEAlderson/EssentialsWarpGUI/commit/735e5540db3fce8ed6a10b67772c6539688c74b9
I'll release the update very soon. Thank you a lot for reporting it!
